language: node_js
node_js:
  - '14'
cache:
  directories:
    - node_modules
dist: trusty
sudo: required
install:
  - npm install
branches:
  only:
    - main
before_script:
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: main
